apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: billing
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: billing
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
