apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: billing-mercadopago
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager # ClusterSecretStore criado pela infra (SSM eso/cluster-secret-store-name)
    kind: ClusterSecretStore
  target:
    name: billing-mercadopago
    creationPolicy: Owner
  data:
    - secretKey: MERCADOPAGO_ACCESS_TOKEN
      remoteRef:
        key: auto-repair-shop/prod/mercadopago
        property: access_token
    - secretKey: MERCADOPAGO_WEBHOOK_SECRET
      remoteRef:
        key: auto-repair-shop/prod/mercadopago
        property: webhook_secret
