apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auto-repair-shop-prod

resources:
  - ../../base
  - externalsecret-mercadopago.yaml

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - target:
      kind: Service
      name: billing
    path: nodeport-patch.yaml

images:
  - name: ghcr.io/ivanzao/auto-repair-shop-billing
    newTag: latest
